# Generated by Django 5.2.6 on 2025-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
