# Generated by Django 5.2.6 on 2025-09-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_resetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('retailer', 'Retailer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
