# Generated by Django 5.2.6 on 2025-09-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
