# Generated by Django 5.2.6 on 2025-09-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
