# Generated by Django 5.2.6 on 2025-09-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_resetcode_expires_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetCode',
            new_name='PasswordResetCode',
        ),
    ]
