# Generated by Django 5.2.6 on 2025-09-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
